### ISSUE TITLE
✨ [feat]: 플레이리스트 GET API 구현

### ISSUE THREAD

**Issue by csh0924** [SSU-RETURN/SSU-RETURN-BACK#32]
## 📝 개요
- 플레이리스트 get API구현
## ✔️ To-Do
- [ ] 취향 플레이리스트 get
- [x] AI 플레이리스트 get
- [ ] 사용자 선택 플레이리스트(감정get)
- [ ] 사용자 선택 플레이리스트(날짜get)
- [ ] 사용자 선택 플레이리스트(simple)

## 👀 ETC
- 참고자료 등 기타 내용 작성
