### ISSUE TITLE
:axe:[Fix]: Diary API 수정

### ISSUE THREAD

**Issue by csh0924** [SSU-RETURN/SSU-RETURN-BACK#36]
## 📝 개요
Diary API관련 내용 수정
- Diary에 List<MusicId>가 들어가도록 함
- Diary의 Response 수정
- 그 외 항목 수정
## ✔️ To-Do
- [ ] Diary response에 불필요한 내용 제거
- [ ] Diary가 request에서 List<MusicId>를 받고, 해당 내용
- [ ] Diary의 aiEmotion을 바뀐 프로젝트 구성에 맞게 수정(연관된 부분 포함)
- [ ] 그 외 추가사항 발생 시 수정

## 👀 ETC
- 참고자료 등 기타 내용 작성
