### ISSUE TITLE
:star2:[Update]:MemberPlaylist 등 url 수정

### ISSUE THREAD

**Issue by csh0924** [SSU-RETURN/SSU-RETURN-BACK#43]
## 📝 개요
- 일부 메소드의 url을 더 명확하고 가시성 좋게 수정

## ✔️ To-Do
- [ ] memberperference -> prefernce
- [ ] detail, detail2 -> diary, emotion
- [ ] getPreferencePlaylist 삭제(주석처리)
- [ ] {memberId} 경로에서 삭제
- [ ] memberplaylist->playlist
## 👀 ETC
- 참고자료 등 기타 내용 작성
